### ISSUE TITLE
FE 2.6 show some information,is it right?

### ISSUE THREAD

**Issue by xtvjxk123456** [TKCM/TKCM_Exts#3]
![image](https://user-images.githubusercontent.com/8720281/33813194-4a85958e-de5d-11e7-827c-c8c0c22e1d8a.png)

i can not  figure out what is going .

**Comment by TKCM** [comment]
They are probably deleted nodes in 2.6.
I will update. please wait few days.

**Comment by TKCM** [comment]
I fixed Fill & EmptyDrawingHnalde nodes.
getClosest*** nodes are renamed GetClosest***, so sorry.
