### ISSUE TITLE
i can not figure out what going on.

### ISSUE THREAD

**Issue by xtvjxk123456** [TKCM/TKCM_Exts#4]
![image](https://user-images.githubusercontent.com/8720281/34187906-a31c4a22-e56e-11e7-8e81-beb0c36207ac.png)
check this error ,need your help.

**Comment by TKCM** [comment]
Oops!
Please wait few days.

**Comment by TKCM** [comment]
Sorry for taking long to write you back.
please update & try again.
and feel free to ask :-)

**Comment by TKCM** [comment]
Sorry for taking long to write you back.
please update & try again.
and feel free to ask :-)

**Comment by xtvjxk123456** [comment]
![image](https://user-images.githubusercontent.com/8720281/34398763-6a2fa08e-ebbc-11e7-9c32-b284afd5e4ad.png)

why? should it be automatically enabled when fabric engine started?

**Comment by TKCM** [comment]
failed to push a json file.

Please update again.

**Comment by xtvjxk123456** [comment]
![image](https://user-images.githubusercontent.com/8720281/34593835-5e679890-f208-11e7-851e-2e9f61a9eb5f.png)

great work!
may need to fix it.

**Comment by TKCM** [comment]
My individual license has expired so I can not check it at home.
Please wait for about a week.

**Comment by xtvjxk123456** [comment]
i have a question, please tell me how to register a custom type,
i can not make a custom type to work.
thank you very much!

**Comment by TKCM** [comment]
fixed a issue.

about your question.
TKCM.fpm.json is a manifest. Some path to the custom KL extention module and DFG preset is filled in the manifest.
To load this extension package, write TKCM in require window.
![87](https://user-images.githubusercontent.com/13941074/34832147-66792f66-f72c-11e7-95ab-de327baed760.jpg)

How to make a custom class.
For example, "object" written in Util \ Valve.kl file is the same as Class in Python or C++. and some class function is also written.
Derived classes and polymorphism etc, these like C ++ specification

file path to this KL file has written in the manifesto. So After requesting TKCM, Valve class(object) is possible to use it like Vec3 or PolygonMesh.

The FE official document was also deleted.
FE is gone.

**Comment by xtvjxk123456** [comment]
Thank you very much!!

**Comment by TKCM** [comment]
You are welcome :)
I hope FE will comeback.
